services:
  postgres:
    image: postgres:15
    container_name: friend-bets-db
    environment:
      POSTGRES_DB: friend_bets
      POSTGRES_USER: friend_bets_user
      POSTGRES_PASSWORD: friend_bets_password
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U friend_bets_user -d friend_bets"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local