[toolchain]
anchor_version = "0.31.1"

[features]
resolution = true
skip-lint = false

[programs.testnet]
friends_bets = "9wBsuUoZ4GD6YDvhVWabwUwF6SVjGWryVXKpPGUtrgrW"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "testnet"
wallet = "~/.config/solana/id.json"

[workspace]
members = ["programs/*"]

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = false

[[test.genesis]]
address = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"
program = "target/deploy/friends_bets.so"
