[toolchain]
anchor_version = "0.31.1"
solana_version = "2.1.0"
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
friends_bets = "CqyLTBgj4mbZSowcMu97QWd1qQw86ZnTE3Qtb2YXvPVd"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
